### PR TITLE
build(deps): Upgrade outdated dependencies, supporting frunk v0.4

### PR DESCRIPTION
**Pull request by siketyan**
Added support for frunk v0.4, syn v1.0, proc-macro2 v1.0, quote v1.0, and frunk_proc_macro_helpers v0.1

### CODE REVIEW

**Comment by bossmc** [comment]
Thanks very much for this contribution, welcome!

You've carefully provided support for both `frunk 0.3` _and_ `frunk 0.4` (which I love btw assuming we can make it work) but I think we're only testing the `0.4` compatibility in the `derive-tests` crate.  Maybe we should add a (pair of) features that choose between 0.3 and 0.4 in the tests and run them both in CI?  If you're happy to do that that would be great, otherwise I'm happy to merge this and add the testing later.

In the meantime:

bors try

**Comment by siketyan** [comment]
@bossmc
Thank you for your review.
I tried to test using multiple frunk versions using rename_dependency feature of cargo.
However it does not because the generated code by frunk-enum-derive refers frunk_core absolutely so I could not inject the selected version of frunk.
See https://github.com/yumemi-inc/frunk-enum/commit/c0c5c880e7ffef3121ee9e45a9ce1472b173744a for details.

Could you please help me with that?

**Comment by bossmc** [comment]
Hey, sorry to let this slip, I've also had a play around with cargo's resolver and trying to convince it to pick 0.3.0 when the rest of the code is using 0.3.0 and 0.4.0 similarly.  I've had no luck so I've decided to bite the bullet and just move to 0.4.0 wholesale.

That change is in #31 and I'm going to close this change in favour of that one.  Thanks for the contribution regardless!

**Comment by bossmc** [comment]
In case you're still interested, I've just released version 0.3.0 which supports interworking with (only) frunk version 0.4.0.

**Pull request closed without merging**
